version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: inventory

  auth-service:
    image: shubhammsalunke/inventory-auth-service:latest
    restart: always
    ports:
      - "4001:4001"
    env_file:
      - ./server/auth-service/.env
    depends_on:
      - mongo

  product-service:
    image: shubhammsalunke/inventory-product-service:latest
    restart: always
    ports:
      - "4002:4002"
    env_file:
      - ./server/product-service/.env
    depends_on:
      - mongo

  api-gateway:
    image: shubhammsalunke/inventory-api-gateway:latest
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./server/api-gateway/.env
    depends_on:
      - auth-service
      - product-service

  client:
    image: shubhammsalunke/inventory-client:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-gateway

volumes:
  mongo_data: